<!-- Licensed to the .NET Foundation under one or more agreements. The .NET Foundation licenses this file to you under the MIT license. -->
<Project>
  <Target Name="CreateHelixPayload" Returns="@(HelixWorkItem)">
    <PropertyGroup>
      <_HelixTestOutputDir>$(ArtifactsBinDir)$(MSBuildProjectName)/$(Configuration)/$(NetCoreAppTestTargetFramework)/</_HelixTestOutputDir>
      <_HelixPayloadDir>$(ArtifactsDir)helix/$(MSBuildProjectName)/$(TargetRid)/$(Configuration)/$(HelixTargetQueue)/payload</_HelixPayloadDir>
    </PropertyGroup>
    <Error Condition="!Exists('$(_HelixTestOutputDir)$(AssemblyName).dll')"
           Text="The prebuilt test assembly '$(_HelixTestOutputDir)$(AssemblyName).dll' was not found." />
    <Error Condition="'$(TestHostRuntimeVersion)' == ''" Text="TestHostRuntimeVersion must specify the test-host runtime." />
    <ItemGroup>
      <_HelixTestOutputFile Include="$(_HelixTestOutputDir)**/*" />
    </ItemGroup>
    <RemoveDir Directories="$(_HelixPayloadDir)" />
    <MakeDir Directories="$(_HelixPayloadDir)" />
    <Copy SourceFiles="@(_HelixTestOutputFile)"
          DestinationFiles="@(_HelixTestOutputFile->'$(_HelixPayloadDir)/tests/$(AssemblyName)/%(RecursiveDir)%(Filename)%(Extension)')" />
    <Copy SourceFiles="$(MSBuildThisFileDirectory)run-tests.sh" DestinationFiles="$(_HelixPayloadDir)/runtests.sh" />
    <ItemGroup>
      <HelixWorkItem Include="$(AssemblyName)">
        <PayloadDirectory>$(_HelixPayloadDir)</PayloadDirectory>
        <Command>bash ./runtests.sh --runtime-version &quot;$(TestHostRuntimeVersion)&quot; --test-dll &quot;tests/$(AssemblyName)/$(AssemblyName).dll&quot; --helix-work-item &quot;$(AssemblyName)&quot;</Command>
        <Timeout>00:30:00</Timeout>
        <RequiredRuntimeVersions>$(TestHostRuntimeVersion)</RequiredRuntimeVersions>
      </HelixWorkItem>
    </ItemGroup>
  </Target>
</Project>
