id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: '[Idle Issue Management] Close stale issues'
      frequencies:
      - weekday:
          day: Monday
          time: 0:0
      - weekday:
          day: Tuesday
          time: 0:0
      - weekday:
          day: Wednesday
          time: 0:0
      - weekday:
          day: Thursday
          time: 0:0
      - weekday:
          day: Friday
          time: 0:0
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Needs: Author Feedback'
      - hasLabel:
          label: 'Status: No Recent Activity'
      - noActivitySince:
          days: 3
      actions:
      - addReply:
          reply: Hi @${issueAuthor}. We are closing this issue due to inactivity. If you comment within 30 days it will automatically reopen. If you are not the author of this issue and you're facing the same problem, feel free to open a new issue referencing this one.
      - closeIssue
    - description: '[Idle Issue Management] Add no recent activity label to issues'
      frequencies:
      - weekday:
          day: Monday
          time: 0:0
      - weekday:
          day: Tuesday
          time: 0:0
      - weekday:
          day: Wednesday
          time: 0:0
      - weekday:
          day: Thursday
          time: 0:0
      - weekday:
          day: Friday
          time: 0:0
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Needs: Author Feedback'
      - noActivitySince:
          days: 4
      - isNotLabeledWith:
          label: 'Status: No Recent Activity'
      actions:
      - addLabel:
          label: 'Status: No Recent Activity'
      - addReply:
          reply: This issue has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **4 days**. It will be closed if no further activity occurs **within 3 days of this comment**. If it *is* closed, feel free to comment when you are able to provide the additional information and we will re-investigate.
    - description: '[Resolved Issue Management] Close resolved issues'
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Status: Resolved'
      - noActivitySince:
          days: 1
      actions:
      - addReply:
          reply: This issue has been resolved and has not had any activity for **1 day**. It will be closed for housekeeping purposes.
      - closeIssue
    eventResponderTasks:
    - description: Auto approve dependencies
      if:
      - payloadType: Pull_Request
      - isPullRequest
      - isAction:
          action: Opened
      - titleContains:
          pattern: Update dependencies
          isRegex: False
      - isActivitySender:
          user: dotnet-maestro[bot]
          issueAuthor: False
      then:
      - approvePullRequest:
          comment: Automatically approving dependency update.
      triggerOnOwnActions: false
    - description: '[Idle Issue Management] Replace needs author feedback label with needs attention label when the author comments on an issue'
      if:
      - payloadType: Issue_Comment
      - isAction:
          action: Created
      - hasLabel:
          label: 'Needs: Author Feedback'
      - isIssue
      - isOpen
      - isActivitySender:
          issueAuthor: True
      then:
      - addLabel:
          label: 'Needs: Attention :wave:'
      - removeLabel:
          label: 'Needs: Author Feedback'
      triggerOnOwnActions: false
    - description: '[Idle Issue Management] Reopen issues with author feedback within 30 days of closure'
      if:
      - payloadType: Issue_Comment
      - isAction:
          action: Created
      - isActivitySender:
          issueAuthor: true
      - hasLabel:
          label: 'Needs: Author Feedback'
      - hasLabel:
          label: 'Status: No Recent Activity'
      - isIssue
      - not:
          and:
          - isOpen
          - isLocked
      then:
      - addLabel:
          label: 'Needs: Attention :wave:'
      - removeLabel:
          label: 'Status: No Recent Activity'
      - removeLabel:
          label: 'Needs: Author Feedback'
      - reopenIssue
      triggerOnOwnActions: false
    - description: '[Closed Issue Management] Remove no recent activity label from issues'
      if:
      - payloadType: Issues
      - not:
          isAction:
            action: Closed
      - isIssue
      - hasLabel:
          label: 'Status: No Recent Activity'
      then:
      - removeLabel:
          label: 'Status: No Recent Activity'
      triggerOnOwnActions: false
    - description: '[Idle Issue Management] Remove no recent activity label when an issue is commented on'
      if:
      - payloadType: Issue_Comment
      - isIssue
      - hasLabel:
          label: 'Status: No Recent Activity'
      then:
      - removeLabel:
          label: 'Status: No Recent Activity'
      triggerOnOwnActions: false
    - description: Add comment when 'Needs Author Feedback' is applied to issue
      if:
      - payloadType: Issues
      - isIssue
      - labelAdded:
          label: 'Needs: Author Feedback'
      then:
      - addReply:
          reply: 'Hi @${issueAuthor}. We have added the "Needs: Author Feedback" label to this issue, which indicates that we have an open question for you before we can take further action. This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.'
      triggerOnOwnActions: false
onFailure: 
onSuccess: 
