trigger:
- master
- release/*

pr:
- master
- release/*

jobs:
- template: /eng/build.yml
  parameters:
    name: Windows
    osGroup: Windows_NT
    strategy:
      parallel: 2
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64
        Build_Release:
          _BuildConfig: Release
          _BuildArch: x64

- template: /eng/build.yml
  parameters:
    name: CentOS_7
    osGroup: Linux
    dockerImage: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-3e800f1-20190501005343
    strategy:
      parallel: 2
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64
        Build_Release:
          _BuildConfig: Release
          _BuildArch: x64

- template: /eng/build.yml
  parameters:
    name: MacOS
    osGroup: MacOS
    strategy:
      parallel: 2
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64
        Build_Release:
          _BuildConfig: Release
          _BuildArch: x64

