trigger:
- master
- release/*

pr:
- master
- release/*

jobs:
- template: /eng/build.yml
  parameters:
    name: MacOS
    osGroup: MacOS
    strategy:
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64
        Build_Release:
          _BuildConfig: Release
          _BuildArch: x64

