phases:
- template: /eng/build.yml
  parameters:
    name: Windows
    agentOs: Windows_NT
    queue: 
      name: Hosted VS2017
      parallel: 4
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64
        Build_Release:
          _BuildConfig: Release
          _BuildArch: x64
          _PublishArtifacts: bin
        Build_Release_x86:
          _BuildConfig: Release
          _BuildArch: x86
          _PublishArtifacts: bin/Windows_NT.x86.Release
        Build_Release_arm:
          _BuildConfig: Release
          _BuildArch: arm
          _PublishArtifacts: bin/Windows_NT.arm.Release

- template: /eng/build.yml
  parameters:
    name: CentOS_7
    agentOs: Linux
    dockerImage: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-3e800f1-20190501005343
    queue:
      name: Hosted Ubuntu 1604
      parallel: 2
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64
          _PublishArtifacts: bin/Linux.x64.Debug
        Build_Release:
          _BuildConfig: Release
          _BuildArch: x64
          _PublishArtifacts: bin/Linux.x64.Release

- template: /eng/build.yml
  parameters:
    name: Linux_cross
    agentOs: Linux
    dockerImage: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-14.04-cross-1735d26-20190521133857
    crossrootfsDir: '/crossrootfs/arm'
    queue:
      name: Hosted Ubuntu 1604
      matrix:
        Build_Release:
          _BuildConfig: Release
          _BuildArch: arm
          _PublishArtifacts: bin/Linux.arm.Release

- template: /eng/build.yml
  parameters:
    name: Linux_cross64
    agentOs: Linux
    dockerImage: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-cross-arm64-a3ae44b-20180315221921
    crossrootfsDir: '/crossrootfs/arm64'
    queue:
      name: Hosted Ubuntu 1604
      matrix:
        Build_Release:
          _BuildConfig: Release
          _BuildArch: arm64
          _PublishArtifacts: bin/Linux.arm64.Release

- template: /eng/build.yml
  parameters:
    name: Alpine3_6
    agentOs: Linux
    dockerImage: mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.6-WithNode-f4d3fe3-20181220200247
    queue:
      name: Hosted Ubuntu 1604
      matrix:
        Build_Release:
          _BuildConfig: Release
          _BuildArch: x64
          _PublishArtifacts: bin/Linux.x64.Release

- template: /eng/build.yml
  parameters:
    name: MacOS
    agentOs: Darwin
    queue: 
      name: Hosted macOS
      parallel: 2
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64
        Build_Release:
          _BuildConfig: Release
          _BuildArch: x64
          _PublishArtifacts: bin/OSX.x64.Release

- template: /eng/build.yml
  parameters:
    name: Debian_Stretch
    agentOs: Linux
    dockerImage: mcr.microsoft.com/dotnet-buildtools/prereqs:debian-stretch-3e800f1-20190521154431
    dependsOn: CentOS_7
    testOnly: true
    queue:
      name: Hosted Ubuntu 1604
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64

- template: /eng/build.yml
  parameters:
    name: Fedora_28
    agentOs: Linux
    dockerImage: mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-28-09ca40b-20190508143249
    dependsOn: CentOS_7
    testOnly: true
    queue:
      name: Hosted Ubuntu 1604
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64

- template: /eng/build.yml
  parameters:
    name: Fedora_29
    agentOs: Linux
    dockerImage: mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-29-09ca40b-20190508143249
    dependsOn: CentOS_7
    testOnly: true
    queue:
      name: Hosted Ubuntu 1604
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64

- template: /eng/build.yml
  parameters:
    name: OpenSuse_42_1
    agentOs: Linux
    dockerImage: mcr.microsoft.com/dotnet-buildtools/prereqs:opensuse-42.1-c103199-20180628122439
    dependsOn: CentOS_7
    testOnly: true
    queue:
      name: Hosted Ubuntu 1604
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64

- template: /eng/build.yml
  parameters:
    name: OpenSuse_42_3
    agentOs: Linux
    dockerImage: mcr.microsoft.com/dotnet-buildtools/prereqs:opensuse-42.3-3e800f1-20190501005344
    dependsOn: CentOS_7
    testOnly: true
    queue:
      name: Hosted Ubuntu 1604
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64

- template: /eng/build.yml
  parameters:
    name: Ubuntu_14_04
    agentOs: Linux
    dockerImage: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-14.04-1735d26-20190521133852
    dependsOn: CentOS_7
    testOnly: true
    queue:
      name: Hosted Ubuntu 1604
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64

- template: /eng/build.yml
  parameters:
    name: Ubuntu_16_04
    agentOs: Linux
    dockerImage: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-09ca40b-20190520220842
    dependsOn: CentOS_7
    testOnly: true
    queue:
      name: Hosted Ubuntu 1604
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64

- template: /eng/build.yml
  parameters:
    name: Ubuntu_18_04
    agentOs: Linux
    dockerImage: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-3e800f1-20190508143252
    dependsOn: CentOS_7
    testOnly: true
    queue:
      name: Hosted Ubuntu 1604
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64

- phase: Sign_Package_Publish
  dependsOn:
  - Windows
  - CentOS_7
  - Alpine3_6
  - MacOS
  - Linux_cross
  - Linux_cross64
  condition: ne(variables['Build.Reason'], 'Schedule')
  queue:
    name: Hosted VS2017
  variables:
    - name: _PublishBlobFeedUrl
      value: https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
    - name: _SOSNETCorePath
      value: $(Build.SourcesDirectory)/artifacts/bin/SOS.NETCore/Release/netstandard2.0/publish
    - name: _TeamName
      value: DotNetCore

  steps:
  # Windows x64 download, copy and archive. Everything under "bin" is published for the Windows x64 build.
  - task: DownloadBuildArtifacts@0
    displayName: Download Windows x64 and Managed Artifacts
    inputs:
      artifactName: Windows_x64_Release
      downloadPath: '$(System.ArtifactsDirectory)'
    condition: succeeded()

  - task: CopyFiles@2
    displayName: Copy Windows Artifacts
    inputs:
      sourceFolder: '$(System.ArtifactsDirectory)/Windows_x64_Release'
      targetFolder: '$(Build.SourcesDirectory)/artifacts/bin'
    condition: succeeded()

  - task: CopyFiles@2
    displayName: Copy Windows x64 Artifacts
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/artifacts/bin/Windows_NT.x64.Release'
      contents: 'sos.dll'
      targetFolder: '$(Build.SourcesDirectory)/artifacts/Windows_NT.x64.Release'
    condition: succeeded()

  - task: CopyFiles@2
    displayName: Copy Windows x64 Artifacts
    inputs:
      sourceFolder: '$(_SOSNETCorePath)'
      contents: '*.dll'
      overWrite: true
      targetFolder: '$(Build.SourcesDirectory)/artifacts/Windows_NT.x64.Release'
    condition: succeeded()

  # Windows x86 download, copy and archive.

  - task: DownloadBuildArtifacts@0
    displayName: Download Windows x86 Artifacts
    inputs:
      artifactName: Windows_x86_Release
      downloadPath: '$(System.ArtifactsDirectory)'
    condition: succeeded()

  - task: CopyFiles@2
    displayName: Copy Windows x86 Artifacts
    inputs:
      sourceFolder: '$(System.ArtifactsDirectory)/Windows_x86_Release'
      contents: 'sos.dll'
      targetFolder: '$(Build.SourcesDirectory)/artifacts/bin/Windows_NT.x86.Release'
    condition: succeeded()

  - task: CopyFiles@2
    displayName: Copy Windows x86 Artifacts
    inputs:
      sourceFolder: '$(_SOSNETCorePath)'
      contents: '*.dll'
      overWrite: true
      targetFolder: '$(Build.SourcesDirectory)/artifacts/bin/Windows_NT.x86.Release'
    condition: succeeded()

  # Windows arm download, copy and archive.

  - task: DownloadBuildArtifacts@0
    displayName: Download Windows Arm Artifacts
    inputs:
      artifactName: Windows_arm_Release
      downloadPath: '$(System.ArtifactsDirectory)'
    condition: succeeded()

  - task: CopyFiles@2
    displayName: Copy Windows Arm Artifacts
    inputs:
      sourceFolder: '$(System.ArtifactsDirectory)/Windows_arm_Release'
      contents: 'sos.dll'
      targetFolder: '$(Build.SourcesDirectory)/artifacts/bin/Windows_NT.arm.Release'
    condition: succeeded()

  - task: CopyFiles@2
    displayName: Copy Windows x86 Artifacts
    inputs:
      sourceFolder: '$(_SOSNETCorePath)'
      contents: '*.dll'
      overWrite: true
      targetFolder: '$(Build.SourcesDirectory)/artifacts/bin/Windows_NT.arm.Release'
    condition: succeeded()

  # Copy and archive the files for windbg extension gallery.

  - powershell: $(Build.SourcesDirectory)\eng\create-gallery-zip.ps1 $(Build.SourcesDirectory)
    displayName: Create Extension Gallery Zip File
    condition: succeeded()

  # Linux x64 download, copy and archive

  - task: DownloadBuildArtifacts@0
    displayName: Download Linux Artifacts
    inputs:
      artifactName: CentOS_7_x64_Release
      downloadPath: '$(System.ArtifactsDirectory)'
    condition: succeeded()

  - task: CopyFiles@2
    displayName: Copy Linux Artifacts
    inputs:
      sourceFolder: '$(System.ArtifactsDirectory)/CentOS_7_x64_Release'
      contents: ?(libsos.so|libsosplugin.so|sosdocsunix.txt)
      targetFolder: '$(Build.SourcesDirectory)/artifacts/bin/Linux.x64.Release'
    condition: succeeded()

  - task: CopyFiles@2
    displayName: Copy Linux Artifacts
    inputs:
      sourceFolder: '$(_SOSNETCorePath)'
      contents: '*.dll'
      overWrite: true
      targetFolder: '$(Build.SourcesDirectory)/artifacts/bin/Linux.x64.Release'
    condition: succeeded()

  # Linux MUSL x64 download, copy and archive

  - task: DownloadBuildArtifacts@0
    displayName: Download Linux Musl Artifacts
    inputs:
      artifactName: Alpine3_6_x64_Release
      downloadPath: '$(System.ArtifactsDirectory)'
    condition: succeeded()

  - task: CopyFiles@2
    displayName: Copy Linux Musl Artifacts
    inputs:
      sourceFolder: '$(System.ArtifactsDirectory)/Alpine3_6_x64_Release'
      contents: ?(libsos.so|libsosplugin.so|sosdocsunix.txt)
      targetFolder: '$(Build.SourcesDirectory)/artifacts/bin/Linux-musl.x64.Release'
    condition: succeeded()

  - task: CopyFiles@2
    displayName: Copy Linux Musl Artifacts
    inputs:
      sourceFolder: '$(_SOSNETCorePath)'
      contents: '*.dll'
      overWrite: true
      targetFolder: '$(Build.SourcesDirectory)/artifacts/bin/Linux-musl.x64.Release'
    condition: succeeded()

  # Linux arm download, copy and archive

  - task: DownloadBuildArtifacts@0
    displayName: Download Linux Arm Artifacts
    inputs:
      artifactName: Linux_cross_arm_Release
      downloadPath: '$(System.ArtifactsDirectory)'
    condition: succeeded()

  - task: CopyFiles@2
    displayName: Copy Linux Arm Artifacts
    inputs:
      sourceFolder: '$(System.ArtifactsDirectory)/Linux_cross_arm_Release'
      contents: ?(libsos.so|libsosplugin.so|sosdocsunix.txt)
      targetFolder: '$(Build.SourcesDirectory)/artifacts/bin/Linux.arm.Release'
    condition: succeeded()

  - task: CopyFiles@2
    displayName: Copy Linux Arm Artifacts
    inputs:
      sourceFolder: '$(_SOSNETCorePath)'
      contents: '*.dll'
      overWrite: true
      targetFolder: '$(Build.SourcesDirectory)/artifacts/bin/Linux.arm.Release'
    condition: succeeded()

  # Linux arm64 download, copy and archive

  - task: DownloadBuildArtifacts@0
    displayName: Download Linux Arm64 Artifacts
    inputs:
      artifactName: Linux_cross64_arm64_Release
      downloadPath: '$(System.ArtifactsDirectory)'
    condition: succeeded()

  - task: CopyFiles@2
    displayName: Copy Linux Arm64 Artifacts
    inputs:
      sourceFolder: '$(System.ArtifactsDirectory)/Linux_cross64_arm64_Release'
      contents: ?(libsos.so|libsosplugin.so|sosdocsunix.txt)
      targetFolder: '$(Build.SourcesDirectory)/artifacts/bin/Linux.arm64.Release'
    condition: succeeded()

  - task: CopyFiles@2
    displayName: Copy Linux Arm64 Artifacts
    inputs:
      sourceFolder: '$(_SOSNETCorePath)'
      contents: '*.dll'
      overWrite: true
      targetFolder: '$(Build.SourcesDirectory)/artifacts/bin/Linux.arm64.Release'

    condition: succeeded()
  # MacOS download, copy and archive

  - task: DownloadBuildArtifacts@0
    displayName: Download MacOS Artifacts
    inputs:
      artifactName: MacOS_x64_Release
      downloadPath: '$(System.ArtifactsDirectory)'
    condition: succeeded()

  - task: CopyFiles@2
    displayName: Copy MacOS Artifacts
    inputs:
      sourceFolder: '$(System.ArtifactsDirectory)/MacOS_x64_Release'
      contents: ?(libsos.dylib|libsosplugin.dylib|sosdocsunix.txt)
      targetFolder: '$(Build.SourcesDirectory)/artifacts/bin/OSX.x64.Release'
    condition: succeeded()

  - task: CopyFiles@2
    displayName: Copy MacOS Artifacts
    inputs:
      sourceFolder: '$(_SOSNETCorePath)'
      contents: '*.dll'
      overWrite: true
      targetFolder: '$(Build.SourcesDirectory)/artifacts/bin/OSX.x64.Release'
    condition: succeeded()

  # Create nuget package and sign binaries

  - script: $(Build.SourcesDirectory)\eng\cipack.cmd
      -configuration Release
      -prepareMachine 
      /p:TeamName=$(_TeamName)
      /p:DotNetSignType=$(SignType) 
      /p:DotNetPublishBlobFeedKey=$(dotnetfeed-storage-access-key-1) 
      /p:DotNetPublishBlobFeedUrl=$(_PublishBlobFeedUrl)
      /p:DotNetPublishToBlobFeed=true
      /p:DotNetSymbolServerTokenMsdl=$(microsoft-symbol-server-pat)
      /p:DotNetSymbolServerTokenSymWeb=$(symweb-symbol-server-pat)
      /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
    displayName: Sign / Package
    continueOnError: true
    condition: succeeded()

  - task: PublishBuildArtifacts@1
    displayName: Publish Package Artifacts
    inputs:
      publishLocation: Container
      pathtoPublish: '$(Build.SourcesDirectory)/artifacts/packages'
      artifactName: Packages
    condition: succeeded()

  - task: PublishBuildArtifacts@1
    displayName: Publish Logs Artifacts
    inputs:
      publishLocation: Container
      pathtoPublish: '$(Build.SourcesDirectory)/artifacts/log'
      artifactName: Logs_Packaging_Signing
    continueOnError: true
    condition: always()
