phases:
- template: /eng/build.yml
  parameters:
    phaseName: MacOS
    agentOs: Darwin
    buildReason: IndividualCI
    queue: 
      name: Hosted macOS Preview
      demands:
        - agent.os -equals Darwin
      parallel: 2
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _PublishType: none
          _SignType: test
