phases:
- template: /eng/build.yml
  parameters:
    agentOs: Windows_NT
    buildReason: Internal
    queue:
      name: DotNetCore-Build
      demands:
      - agent.os -equals Windows_NT
      parallel: 2
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _PublishType: none
          _SignType: test
        Build_Release:
          _BuildConfig: Release
          _PublishType: blob
          _SignType: real

- template: /eng/build.yml
  parameters:
    agentOs: Linux
    buildReason: Internal
    dockerImage: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304
    queue:
      name: DotNetCore-Test
      demands:
      - agent.os -equals Linux
      parallel: 2
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _PublishType: none
          _SignType: test
        Build_Release:
          _BuildConfig: Release
          _PublishType: none
          _SignType: real
