<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsHelixTestProject>true</IsHelixTestProject>
    <TargetFrameworks>$(SupportedXUnitTestTargetFrameworks)</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SrcDir)Microsoft.Diagnostics.ExtensionCommands\Microsoft.Diagnostics.ExtensionCommands.csproj" />
  </ItemGroup>

  <Import Project="..\Helix\Managed\HelixPayload.targets" Condition="'$(TargetRid)' == 'linux-x64'" />

</Project>
