<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework Condition="'$(BuildProjectFramework)' != ''">$(BuildProjectFramework)</TargetFramework>
    <TargetFrameworks Condition="'$(BuildProjectFramework)' == ''">$(SupportedSubProcessTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>
  <Target Name="WriteDbgShimSingleFileRuntimeVersion"
          AfterTargets="Publish"
          Condition="'$(DbgShimSingleFileRuntimeVersion)' != ''">
    <WriteLinesToFile File="$(PublishDir)runtime.version"
                      Lines="$(DbgShimSingleFileRuntimeVersion)"
                      Overwrite="true"
                      WriteOnlyWhenDifferent="true" />
  </Target>
</Project>
