# build.yml
# Description: Defines the build phase
# Parameters:
#   agentOs: [Windows_NT (default), Linux, OSX] Used in templates to define variables which are OS specific
#   dockerImage: If defined, specifies docker image to run build steps in
#   matrix: build matrix
#   enableTelemetry: send telemetry if build is not a PR or CI build
#   queue YAML object - https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-schema.md#queue
#   variables YAML object - https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-schema.md#phase

parameters:
  phaseName: ''
  agentOs: Windows_NT
  dockerImage: ''
  testOnly: false
  dependsOn: ''
  enableTelemetry: true
  queue: {}
  variables: {}

phases:
- template: /eng/common/templates/phases/base.yml
  parameters:
    name: ${{ parameters.phaseName }}
    agentOs: ${{ parameters.agentOs }}
    dependsOn: ${{ parameters.dependsOn }}
    enableTelemetry: ${{ parameters.enableTelemetry }}
    queue: ${{ parameters.queue }}

    variables: 
      ${{ insert }}: ${{ parameters.variables }}
      _PortableLinuxBuild: CentOS_7_Build_$(_BuildConfig)
      _DockerImageName: ${{ parameters.dockerImage }}
      _PhaseName : ${{ parameters.phaseName }}
      _HelixType: build/product
      _HelixBuildConfig: $(_BuildConfig)
      ${{ if ne(variables['System.TeamProject'], 'public') }}:
        _HelixSource: official/dotnet/arcade/$(Build.SourceBranch)
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        _HelixSource: pr/dotnet/arcade/$(Build.SourceBranch)
      ${{ if eq(parameters.testOnly, 'true') }}:
        _LinuxScript: $(Build.SourcesDirectory)/eng/citest.sh
      ${{ if ne(parameters.testOnly, 'true') }}:
        _LinuxScript: $(Build.SourcesDirectory)/eng/cibuild.sh
      ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
        ${{ if eq(parameters.agentOs, 'Windows_NT') }}:
          _DailyTest: -daily-test
        ${{ if ne(parameters.agentOs, 'Windows_NT') }}:
          _DailyTest: --daily-test
      ${{ if ne(variables['Build.Reason'], 'Schedule') }}:
        _DailyTest: ''

    steps:
    # Internal only build steps
    - template: /eng/common/templates/steps/run-on-windows.yml
      parameters:
        agentOs: ${{ parameters.agentOs }} 
        steps:
        - script: $(Build.SourcesDirectory)\eng\cibuild.cmd $(_DailyTest)
            -configuration $(_BuildConfig) 
            -architecture $(_BuildArch)
            -prepareMachine 
          displayName: Build / Test
          env:
            OfficialBuildId: $(BUILD.BUILDNUMBER)
          condition: succeeded()

    - ${{ if eq(parameters.agentOs, 'Linux') }}:
      - ${{ if eq(parameters.testOnly, 'true') }}:
        - task: DownloadBuildArtifacts@0
          displayName: Download Linux-x64 Artifacts
          inputs:
            artifactName: $(_PortableLinuxBuild)
            downloadPath: '$(System.ArtifactsDirectory)'
          condition: succeeded()

        - task: CopyFiles@2
          displayName: Place Linux-x64 Artifacts
          inputs:
            sourceFolder: '$(System.ArtifactsDirectory)/$(_PortableLinuxBuild)'
            targetFolder: '$(Build.SourcesDirectory)/artifacts/$(_BuildConfig)/bin/Linux.x64'
          condition: succeeded()

      - script: $(Build.SourcesDirectory)/eng/docker-build.sh 
          --docker-image $(_DockerImageName)
          --source-directory $(Build.SourcesDirectory)
          --container-name diagnostics-$(Build.BuildId)
          $(_LinuxScript) $(_DailyTest)
          --configuration $(_BuildConfig) 
          --architecture $(_BuildArch)
          --prepareMachine 
          /p:BUILD_BUILDNUMBER=$(BUILD.BUILDNUMBER)
        displayName: Docker Build / Test
        env:
          OfficialBuildId: $(BUILD.BUILDNUMBER)
        condition: succeeded()

    - ${{ if eq(parameters.agentOs, 'Darwin') }}:
      - script: $(Build.SourcesDirectory)/eng/cibuild.sh $(_DailyTest)
          --configuration $(_BuildConfig) 
          --architecture $(_BuildArch)
          --prepareMachine
        displayName: Build / Test
        env:
          OfficialBuildId: $(BUILD.BUILDNUMBER)
        condition: succeeded()
 
    # Internal only build steps (until publishing artifacts in public CI is supported)
    - ${{ if ne(variables['System.TeamProject'], 'public') }}:
      - task: PublishBuildArtifacts@1
        displayName: Upload Artifacts
        inputs:
          pathtoPublish: '$(Build.SourcesDirectory)/artifacts/$(_BuildConfig)/$(_PublishArtifacts)'
          artifactName: $(_PhaseName)_$(Agent.JobName)
        condition: and(succeeded(), ne(variables['_PublishArtifacts'], ''))

      - task: CopyFiles@2
        displayName: Gather Build Logs
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/artifacts/$(_BuildConfig)/log'
          targetFolder: '$(Build.StagingDirectory)/BuildLogs'
        continueOnError: true
        condition: always()

      - task: CopyFiles@2
        displayName: Gather Test Logs
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/artifacts/$(_BuildConfig)/TestResults'
          targetFolder: '$(Build.StagingDirectory)/BuildLogs'
        continueOnError: true
        condition: always()

      - task: PublishBuildArtifacts@1
        displayName: Publish Logs to VSTS
        inputs:
          pathtoPublish: '$(Build.StagingDirectory)/BuildLogs'
          artifactName: Logs_$(_PhaseName)_$(Agent.JobName)
        continueOnError: true
        condition: always()
