parameters:
  # Optional: Clean sources before building
  clean: true

  # Optional: Git fetch depth
  fetchDepth: ''

  # Optional: name of the phase (not specifying phase name may cause name collisions)
  name: ''

  # Phase dependencies
  dependsOn: ''

  # Required: A defined YAML queue
  queue: {}

  # Required: build steps
  steps: []

  # Optional: variables
  variables: {}

  ## Telemetry variables

  # Optional: enable sending telemetry
  #           if 'true', these "variables" must be specified in the variables object or as part of the queue matrix
  #             _HelixBuildConfig - differentiate between Debug, Release, other
  #             _HelixSource - Example: build/product
  #             _HelixType - Example: official/dotnet/arcade/$(Build.SourceBranch)
  enableTelemetry: false

phases:
- phase: ${{ parameters.name }}

  dependsOn: ${{ parameters.dependsOn }}

  queue: ${{ parameters.queue }}

  ${{ if ne(parameters.variables, '') }}:
    variables: ${{ parameters.variables }}

  steps:
  - checkout: self
    clean: ${{ parameters.clean }}
    ${{ if ne(parameters.fetchDepth, '') }}:
      fetchDepth: ${{ parameters.fetchDepth }}

  - ${{ if eq(parameters.enableTelemetry, 'true') }}:
    - template: /eng/common/templates/steps/telemetry-start.yml
      parameters:
        buildConfig: $(_HelixBuildConfig)
        helixSource: $(_HelixSource)
        helixType: $(_HelixType)

  # Run provided build steps
  - ${{ parameters.steps }}

  - ${{ if eq(parameters.enableMicrobuild, 'true') }}:
    # Internal only resources
    - ${{ if ne(variables['System.TeamProject'], 'public') }}:
      - task: MicroBuildCleanup@1
        displayName: Execute Microbuild cleanup tasks  
        condition: and(always(), in(variables['_SignType'], 'real', 'test'), eq(variables['Agent.Os'], 'Windows_NT'))
        env:
          TeamName: $(_TeamName)

  - ${{ if eq(parameters.enableTelemetry, 'true') }}:
    - template: /eng/common/templates/steps/telemetry-end.yml
      parameters:
        helixSource: $(_HelixSource)
        helixType: $(_HelixType)
