parameters:
  # Optional: Clean sources before building
  clean: true

  # Optional: Git fetch depth
  fetchDepth: ''

  # Optional: name of the phase (not specifying phase name may cause name collisions)
  name: ''

  # Phase dependencies
  dependsOn: ''

  # Required: A defined YAML queue
  queue: {}

  # Required: build steps
  steps: []

  # Optional: variables
  variables: {}

  ## Telemetry variables

  # Required: determines whether to run cmd or sh telemetry files
  agentOs: Windows_NT

  # Optional: enable sending telemetry
  #           if enabled, these "variables" must be specified in the variables object
  #             _HelixBuildConfig - differentiate between Debug, Release, other
  #             _HelixSource - Example: build/product
  #             _HelixType - Example: official/dotnet/arcade/$(Build.SourceBranch)
  enableTelemetry: false

phases:
- phase: ${{ parameters.name }}

  dependsOn: ${{ parameters.dependsOn }}

  queue: ${{ parameters.queue }}

  ${{ if ne(parameters.variables, '') }}:
    variables: ${{ parameters.variables }}

  steps:
  - checkout: self
    clean: ${{ parameters.clean }}
    ${{ if ne(parameters.fetchDepth, '') }}:
      fetchDepth: ${{ parameters.fetchDepth }}

  - ${{ if eq(parameters.enableTelemetry, 'true') }}:
    # Remove this condition once telemetry can be sent from public CI
    - ${{ if notIn(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'PullRequest') }}:
      - template: /eng/common/templates/steps/telemetry-start.yml
        parameters:
          agentOs: ${{ parameters.agentOs }}
          buildConfig: ${{ parameters.variables._HelixBuildConfig }}
          helixSource: ${{ parameters.variables._HelixSource }}
          helixType: ${{ parameters.variables._HelixType }}

  # Run provided build steps
  - ${{ parameters.steps }}

  - ${{ if eq(parameters.enableTelemetry, 'true') }}:
    # Remove this condition once telemetry can be sent from public CI
    - ${{ if notIn(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'PullRequest') }}:
      - template: /eng/common/templates/steps/telemetry-end.yml
        parameters:
          agentOs: ${{ parameters.agentOs }}
          helixSource: ${{ parameters.variables._HelixSource }}
          helixType: ${{ parameters.variables._HelixType }}
