// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

HOST_RUNTIME_ASSEMBLY("System.Collections.Immutable.dll", 8, 10)
HOST_RUNTIME_ASSEMBLY("System.Diagnostics.DiagnosticSource.dll", 8, 10)
HOST_RUNTIME_ASSEMBLY("System.IO.Pipelines.dll", 9, 10)
HOST_RUNTIME_ASSEMBLY("System.Text.Encodings.Web.dll", 8, 10)
HOST_RUNTIME_ASSEMBLY("System.Text.Json.dll", 8, 10)
