<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(NetCoreAppMinTargetFramework)</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsTestProject>false</IsTestProject>
    <IsPackable>false</IsPackable>
    <PublishAot>true</PublishAot>
    <IsAotCompatible>true</IsAotCompatible>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Microsoft.FileFormats\Microsoft.FileFormats.csproj" />
    <Compile Include="..\RegisteredScenarios.cs" Link="RegisteredScenarios.cs" />
    <Content Include="..\TestBinaries\**\*" Link="TestBinaries\%(RecursiveDir)%(Filename)%(Extension)"
             CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
