stages:
- stage: PrepareReleaseStage
  displayName: Release Preparation
  jobs:
  - job: PrepareReleaseJob
    displayName: Prepare Release
    ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')) }}:
      templateContext:
        outputs:
        - output: pipelineArtifact
          path: '$(System.ArtifactsDirectory)\ReleaseStaging'
          artifact: DiagnosticsRelease
          displayName: 'Publish Release Drop'
          condition: succeeded()
    variables:
    - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')) }}:
      - group: DotNet-Diagnostics-Storage
      - group: Release-Pipeline
    steps:
    - ${{ if in(variables['Build.Reason'], 'PullRequest') }}:
      - script: '$(Build.Repository.LocalPath)\dotnet.cmd build $(Build.Repository.LocalPath)\eng\release\DiagnosticsReleaseTool\DiagnosticsReleaseTool.csproj -c Release /bl'
        workingDirectory: '$(System.ArtifactsDirectory)'
        displayName: 'Build Manifest generation and asset publishing tool'
    - ${{ elseif and(ne(variables['System.TeamProject'], 'public'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')) }}:
      - task: UseDotNet@2
        displayName: 'Use .NET Core runtime 6.x'
        inputs:
          packageType: runtime
          version: 6.x
          installationPath: '$(Build.Repository.LocalPath)\.dotnet'
      - template: /eng/common/templates/post-build/setup-maestro-vars.yml

      # Populate dotnetbuilds-internal-container-read-token
      - template: /eng/common/templates-official/steps/get-delegation-sas.yml
        parameters:
          federatedServiceConnection: 'dotnetbuilds-internal-read'
          outputVariableName: 'dotnetbuilds-internal-checksums-container-read-token'
          expiryInHours: 1
          base64Encode: false
          storageAccount: dotnetbuilds
          container: internal-checksums
          permissions: rl

      # Populate dotnetbuilds-internal-container-read-token
      - template: /eng/common/templates-official/steps/get-delegation-sas.yml
        parameters:
          federatedServiceConnection: 'dotnetbuilds-internal-read'
          outputVariableName: 'dotnetbuilds-internal-container-read-token'
          expiryInHours: 1
          base64Encode: false
          storageAccount: dotnetbuilds
          container: internal
          permissions: rl

      - task: AzureCLI@2
        displayName: 'DARC Gather build'
        inputs:
          azureSubscription: "Darc: Maestro Production"
          scriptType: ps
          scriptPath: '$(Build.Repository.LocalPath)/eng/release/Scripts/AcquireBuild.ps1'
          arguments: >-
            -BarBuildId "$(BARBuildId)"
            -ReleaseVersion "$(Build.BuildNumber)"
            -DownloadTargetPath "$(System.ArtifactsDirectory)\ReleaseTarget"
            -AzdoToken "$(dn-bot-all-drop-rw-code-rw-release-all)"
            -SasSuffixes "$(dotnetbuilds-internal-checksums-container-read-token),$(dotnetbuilds-internal-container-read-token)"
          workingDirectory: '$(Build.Repository.LocalPath)'
      - task: AzureCLI@2
        displayName: 'Manifest generation and asset publishing'
        inputs:
          workingDirectory: '$(Build.Repository.LocalPath)\'
          azureSubscription: 'dotnetstage-diagnostics-tools-rw'
          scriptType: pscore
          scriptLocation: inlineScript
          addSpnToEnvironment: true
          inlineScript: |
              $(Build.Repository.LocalPath)\dotnet.cmd run `
                --project $(Build.Repository.LocalPath)\eng\release\DiagnosticsReleaseTool\DiagnosticsReleaseTool.csproj -c Release `
                -- `
                prepare-release `
                --input-drop-path "$(System.ArtifactsDirectory)\ReleaseTarget" `
                --tool-manifest "$(Build.Repository.LocalPath)\eng\release\tool-list.json" `
                --staging-directory "$(System.ArtifactsDirectory)\ReleaseStaging" `
                --release-name "$(Build.BuildNumber)" `
                --account-name "$(dotnet-diagnostics-storage-accountname)" `
                --client-id "$env:servicePrincipalId" `
                --container-name "$(dotnet-diagnostics-container-name)" `
                -v True
