parameters:
- name: pipelineJobTemplate
  type: string
- name: configuration
  type: string
- name: platform
  type: object
- name: isOfficialBuild
  type: boolean
  default: false

jobs:
- template: ${{ parameters.pipelineJobTemplate }}
  parameters:
    name: SOS_Helix_${{ parameters.platform.name }}_${{ parameters.platform.arch }}_${{ parameters.configuration }}
    displayName: SOS Helix ${{ parameters.platform.rid }} ${{ parameters.configuration }}
    timeoutInMinutes: 420
    enableMicrobuild: true

    pool:
      ${{ if eq(parameters.platform.os, 'windows') }}:
        name: $(BuildPool)
        demands: ImageOverride -equals $(WindowsImage)
        os: windows
      ${{ elseif eq(parameters.platform.os, 'linux') }}:
        name: $(BuildPool)
        demands: ImageOverride -equals $(LinuxImage)
        os: linux
      ${{ elseif eq(parameters.platform.os, 'osx') }}:
        name: Azure Pipelines
        vmImage: $(macOSImage)
        os: macOS
      ${{ else }}:
        'error, unsupported OS': ${{ parameters.platform.os }}

    dependsOn: ${{ parameters.platform.name }}_${{ parameters.platform.arch }}_${{ parameters.configuration }}

    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download SOS test payload inputs
      inputs:
        artifact: TestArtifacts_${{ parameters.platform.name }}_${{ parameters.platform.arch }}_${{ parameters.configuration }}
        targetPath: '$(Build.SourcesDirectory)/artifacts'
        checkDownloadedFiles: true

    - powershell: >
        powershell "$env:BUILD_SOURCESDIRECTORY\eng\common\msbuild.ps1
        $env:BUILD_SOURCESDIRECTORY\src\tests\SOS.Tests\SOS.Tests.csproj
        /restore /p:TreatWarningsAsErrors=false /t:SendToHelix
        /p:Configuration=${{ parameters.configuration }}
        /p:TargetArch=${{ parameters.platform.arch }}
        /p:TargetOS=${{ replace(parameters.platform.os, 'windows', 'Windows_NT') }}
        /p:TargetRid=${{ parameters.platform.rid }}
        /p:OfficialBuildId=$env:BUILD_BUILDNUMBER
        /bl:$env:BUILD_SOURCESDIRECTORY\artifacts\log\${{ parameters.configuration }}\SendToHelix.binlog"
      displayName: Run SOS.Tests on Helix
      env:
        HelixSource: pr/dotnet/diagnostics/sos-tests
        HelixType: tests/sos/harness/
        HelixConfiguration: ${{ parameters.platform.rid }}_${{ parameters.configuration }}
        HelixTargetQueues: $(helix_${{ parameters.platform.queueKey }})
        HelixPreCommands: ${{ coalesce(parameters.platform.helixPreCommands, '') }}
        Creator: dotnet-bot
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      condition: eq(variables['Agent.Os'], 'Windows_NT')
      continueOnError: ${{ parameters.isOfficialBuild }}

    - script: >
        $BUILD_SOURCESDIRECTORY/eng/common/msbuild.sh
        $BUILD_SOURCESDIRECTORY/src/tests/SOS.Tests/SOS.Tests.csproj
        /restore /p:TreatWarningsAsErrors=false /t:SendToHelix
        /p:Configuration=${{ parameters.configuration }}
        /p:TargetArch=${{ parameters.platform.arch }}
        /p:TargetOS=${{ replace(parameters.platform.os, 'windows', 'Windows_NT') }}
        /p:TargetRid=${{ parameters.platform.rid }}
        /p:OfficialBuildId=$BUILD_BUILDNUMBER
        /bl:$BUILD_SOURCESDIRECTORY/artifacts/log/${{ parameters.configuration }}/SendToHelix.binlog
      displayName: Run SOS.Tests on Helix
      env:
        HelixSource: pr/dotnet/diagnostics/sos-tests
        HelixType: tests/sos/harness/
        HelixConfiguration: ${{ parameters.platform.rid }}_${{ parameters.configuration }}
        HelixTargetQueues: $(helix_${{ parameters.platform.queueKey }})
        HelixPreCommands: ${{ coalesce(parameters.platform.helixPreCommands, '') }}
        Creator: dotnet-bot
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      condition: ne(variables['Agent.Os'], 'Windows_NT')
      continueOnError: ${{ parameters.isOfficialBuild }}

    - task: CopyFiles@2
      displayName: Gather Helix logs
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)/artifacts'
        contents: '?(log|TestResults)/**'
        targetFolder: '$(Build.StagingDirectory)/HelixLogs'
      continueOnError: true
      condition: always()

    - template: /eng/pipelines/publish-pipeline-artifact-shim.yml@self
      parameters:
        displayName: Publish Helix logs
        inputs:
          targetPath: '$(Build.StagingDirectory)/HelixLogs'
          artifactName: Logs_SOS_Helix_${{ parameters.platform.name }}_${{ parameters.platform.arch }}_${{ parameters.configuration }}_$(System.JobAttempt)
          sbomEnabled: false
        continueOnError: true
        condition: always()
