// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TestTargetsGen;

/// <summary>
/// Source generator that mirrors the <c>public const</c> and <c>public static readonly</c>
/// (literal-initialized) fields of the test targets into the test project, so tests can assert
/// against the target's own declared values with full intellisense:
/// <code>pe.Field("Message").Equals(TestTargets.NestedExceptions.OuterMessage);</code>
///
/// The test-target source files are supplied as <c>AdditionalFiles</c>. Only literal-initialized
/// fields are mirrored (the value is known at compile time), which is exactly the const /
/// static-readonly-constant case — no runtime/ClrMD read is needed. Mirrors are emitted under a
/// single fixed namespace (<see cref="MirrorNamespace"/>) regardless of where the source type
/// lives, since the test targets declare their types in the global namespace.
/// </summary>
[Generator]
public sealed class TestTargetsMirrorGenerator : IIncrementalGenerator
{
    private const string MirrorNamespace = "TestTargets";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<ImmutableArray<string>> sources = context.AdditionalTextsProvider
            .Where(static a => a.Path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
            .Select(static (a, ct) => a.GetText(ct)?.ToString() ?? string.Empty)
            .Collect();

        context.RegisterSourceOutput(sources, static (spc, files) =>
        {
            Dictionary<string, MirrorType> types = new(StringComparer.Ordinal);
            foreach (string file in files)
            {
                foreach (MirrorType type in ParseFile(file))
                {
                    types[type.Name] = type; // last writer wins; names are unique across targets
                }
            }

            if (types.Count == 0)
            {
                return;
            }

            spc.AddSource("TestTargetsMirror.g.cs", SourceText.From(Emit(types.Values), Encoding.UTF8));
        });
    }

    private static string Emit(IEnumerable<MirrorType> types)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").AppendLine(MirrorNamespace);
        sb.AppendLine("{");

        foreach (MirrorType type in types.OrderBy(t => t.Name, StringComparer.Ordinal))
        {
            sb.AppendLine($"    /// <summary>Compile-time mirror of const / static-readonly fields of test target type '{type.Name}'.</summary>");
            sb.AppendLine($"    public static class {type.Name}");
            sb.AppendLine("    {");
            foreach (MirrorField field in type.Fields)
            {
                string kind = field.IsConst ? "const" : "static readonly";
                sb.AppendLine($"        public {kind} {field.Type} {field.Name} = {field.Initializer};");
            }

            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static IEnumerable<MirrorType> ParseFile(string source)
    {
        SyntaxNode root = CSharpSyntaxTree.ParseText(source).GetRoot();

        foreach (TypeDeclarationSyntax type in root.DescendantNodes().OfType<TypeDeclarationSyntax>())
        {
            if (!type.Modifiers.Any(SyntaxKind.PublicKeyword))
            {
                continue;
            }

            List<MirrorField> fields = new();
            foreach (FieldDeclarationSyntax fd in type.Members.OfType<FieldDeclarationSyntax>())
            {
                SyntaxTokenList mods = fd.Modifiers;
                if (!mods.Any(SyntaxKind.PublicKeyword))
                {
                    continue;
                }

                bool isConst = mods.Any(SyntaxKind.ConstKeyword);
                bool isStaticReadonly = mods.Any(SyntaxKind.StaticKeyword) && mods.Any(SyntaxKind.ReadOnlyKeyword);
                if (!isConst && !isStaticReadonly)
                {
                    continue;
                }

                string typeText = fd.Declaration.Type.ToString();
                foreach (VariableDeclaratorSyntax v in fd.Declaration.Variables)
                {
                    if (v.Initializer is null || !IsLiteralLike(v.Initializer.Value))
                    {
                        continue;
                    }

                    fields.Add(new MirrorField(isConst, typeText, v.Identifier.Text, v.Initializer.Value.ToString()));
                }
            }

            if (fields.Count > 0)
            {
                yield return new MirrorType(type.Identifier.Text, fields);
            }
        }
    }

    /// <summary>True for expressions whose value is known at compile time (literals and operators over them).</summary>
    private static bool IsLiteralLike(ExpressionSyntax expr) => expr switch
    {
        LiteralExpressionSyntax => true,
        PrefixUnaryExpressionSyntax u => IsLiteralLike(u.Operand),
        ParenthesizedExpressionSyntax p => IsLiteralLike(p.Expression),
        BinaryExpressionSyntax b => IsLiteralLike(b.Left) && IsLiteralLike(b.Right),
        _ => false,
    };

    private sealed class MirrorType
    {
        public MirrorType(string name, List<MirrorField> fields)
        {
            Name = name;
            Fields = fields;
        }

        public string Name { get; }

        public List<MirrorField> Fields { get; }
    }

    private sealed class MirrorField
    {
        public MirrorField(bool isConst, string type, string name, string initializer)
        {
            IsConst = isConst;
            Type = type;
            Name = name;
            Initializer = initializer;
        }

        public bool IsConst { get; }

        public string Type { get; }

        public string Name { get; }

        public string Initializer { get; }
    }
}
