<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(NetCoreAppTestTargetFramework)</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>SOS.TestHarness.Capturer</AssemblyName>
    <RuntimeIdentifier>$(TargetRid)</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SOS.TestHarness\SOS.TestHarness.csproj" />
  </ItemGroup>

</Project>
